version: '3'

volumes:
  db: {}
  ui: {}
  api: {}

services:
  ui:
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    links: 
      - "api"
    working_dir: /app
    command: "npm run start"
  api:
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    links: 
      - "db:mongo"
    environment:
     - PORT=3001
  db:
    image: mongo:3.5.6
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
    restart: unless-stopped
